CC = clang
FLAGS = -Wall -Wextra


all:
	${CC} ${WFLAGS} -o printchars printchars.c
	${CC} ${WFLAGS} -o sched starter.c
	${CC} ${WFLAGS} -o prio priority.c

clean:
	rm -f printchars
	rm -f sched
	rm -f prio
